config/routes.rb
Greentrack::Application.routes.draw do

    root :to => "projects#index"
    resources :projects, only: [:index, :create, :show] do
        resources :features, only: [:new, :create]
    end

    resources :features, only: [:show] do
        resources :scenarios, only: [:new, :create, :edit, :update]
    end

    resources :scenarios, only: [:show, :create, :edit, :update] do
      resources :steps, only: [:new, :create]
    end
end

app/models/feature.rb
class Feature < ActiveRecord::Base
    attr_accessible :name, :project_id
    validates :project_id, presence: true
    validates :name, presence: true
    belongs_to :project
    has_many :scenarios, :dependent => :destroy

    after_initialize :set_default_name
    def set_default_name
        self.name = "New Feature" if !self.name
    end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  has_many :features, :dependent => :destroy
  validates :name, presence: true
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
    attr_accessible :name, :steps_attributes
    belongs_to :feature
    has_many :steps, :dependent => :destroy
    accepts_nested_attributes_for :steps, :reject_if => lambda { |a| a[:regex].blank? }, :allow_destroy => true

    after_initialize :set_default_name
    def set_default_name
        self.name = "New Scenario" if !self.name
    end
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :prefix, :regex
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

def new
    @feature = Feature.new
end

def create
    @feature = Feature.new(params[:feature])
    @feature.project_id = params[:project_id]
    if @feature.save
        redirect_to @feature
    else
        flash[:error] = "Something went wrong while creating this feature. Please try again."
        render action: :new
    end
end

def show
    @feature = Feature.find(params[:id])
    @scenarios = @feature.scenarios
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

def index
    @projects = Project.all
end

def create
    @project = Project.new(params[:project])
    if @project.save
        redirect_to @project
    else
        render action: :index
    end
end

def show
    @project = Project.find(params[:id])
    @features = @project.features
end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

def new
  @feature = params[:feature_id]
  @scenario = Scenario.new
end

def create
  @scenario = Scenario.new(params[:scenario])
  @scenario.feature_id = params[:feature_id]
  if @scenario.save
    redirect_to edit_feature_scenario_path(params[:feature_id], @scenario)
  else
    flash[:error] = "Something went wrong while creating this scenario. Please try again."
    render action: :new
  end
end

def edit
  @scenario = Scenario.find(params[:id])
  @feature = @scenario.feature
end

def update
  @scenario = Scenario.find(params[:id])
  if @scenario.update_attributes(params[:scenario])
    redirect_to @scenario
  else
    flash[:error] = "Something went wrong while saving this scenario. Please try again."
    render action: :edit
  end
end

def show
    @scenario = Scenario.find params[:id]
    @steps = @scenario.steps
    @feature = @scenario.feature
end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

  def new

  end

  def create

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/features/new.html.erb
<%= form_for @feature, :url => { :action => "create" } do |f| %>
  <%= f.text_field :name %><br>
  <%= f.submit "Save" %>
<% end %>

app/views/features/show.html.erb
<h1><%=@feature.name%></h1>

<h2>Scenarios</h2>

<% if @scenarios.empty? %>
  <p>There are no scenarios for this feature yet.</p>
<% else %>
<ul>
  <% @scenarios.each do |scenario| %>
    <li><%= link_to scenario.name, scenario_path(scenario) %></li>
  <% end %>
</ul>
<% end %>

<%= link_to "New Scenario", new_feature_scenario_path(@feature) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greentrack</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">GreenTrack</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

<div class="container">

<% if flash[:error] %>
  <p class="error"><%= flash[:error] %></p>
<% end %>
<%= yield %>

</div>

</body>
</html>

app/views/projects/index.html.erb
<h1>Current projects</h1><br>
<ul>
<% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
<% end %>
</ul>


<%= form_for Project.new, :url => { :action => "create" } do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/projects/show.html.erb
<h1><%=@project.name%></h1>

<h2>Features</h2>
<ul>
<% @features.each do |feature| %>
  <li><%= link_to feature.name, feature_path(feature) %></li>
<% end %>
</ul>

<%= link_to "Create", new_project_feature_path(@project) %>

app/views/scenarios/_form.html.erb
<%= form_for @scenario do |f| %>
  <p>
    <%= f.text_field :name %>
  </p>
  <h2>Steps</h2>
  <%= f.fields_for :steps do |builder| %>
    <%= render "step_fields", :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add Step", f, :steps %></p>
  <p><%= f.submit "Save" %></p>
<% end %>

app/views/scenarios/_step_fields.html.erb
<p class="fields">
  <%= f.select(:prefix, [['Given', 'Given'], ['When', 'When'], ['Then','Then'], ['And','And'], ['But','But']]) %>
  <%= f.text_field :regex %>
  <%= link_to_remove_fields "remove", f %>
</p>

app/views/scenarios/edit.html.erb
<h1><%=@scenario.name%></h1>
<%= render "form" %>

app/views/scenarios/new.html.erb
<h1>New Scenario</h1>
<%= form_for @scenario, :url => { :action => "create" } do |f| %>
  <%= f.text_field :name %><br>
  <%= f.submit "Create" %>
<% end %>

app/views/scenarios/show.html.erb
<h1><%= @scenario.name %></h1>

<table>
<% @steps.each do |step| %>
  <tr>
  <td><%= step.prefix %></td> <td><%= step.regex %></td>
</tr>
<% end %>
</table>

<%= link_to "Edit", edit_scenario_path(@scenario.id) %>